# Generated by Django 5.1.4 on 2024-12-15 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Commandes', '0001_initial'),
        ('Createur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='createur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Createur.createur'),
        ),
    ]
