# Generated by Django 5.1.4 on 2024-12-07 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clients', '0001_initial'),
        ('Produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitPanier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panier.panier')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produits.produit')),
            ],
        ),
        migrations.AddField(
            model_name='panier',
            name='produits',
            field=models.ManyToManyField(through='panier.ProduitPanier', to='Produits.produit'),
        ),
    ]
